plugins {
    id 'com.android.application'
}

android {
    namespace 'com.audioprobe'
    buildToolsVersion = "36.1.0"
    compileSdk {
        version = release(36)
    }
    ndkVersion "27.2.12479018"

    defaultConfig {
        applicationId "com.audioprobe"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
                abiFilters "arm64-v8a"
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version "3.22.1"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
}
